theme: jekyll-theme-minimal
title: Vincent Gramoli
logo: img/vincent-gramoli.png
timezone: Australia/NSW
description: School of Computer Science <br /> 1, Cleveland St., <br /> NSW 2006 Sydney<br /><a class="twitter-follow-button"
  href="https://twitter.com/VincentGramoli">Follow @VincentGramoli</a><br />
