theme: jekyll-theme-minimal
title: Vincent Gramoli
description: <img src="http://redbellyrw.cluster021.hosting.ovh.net/img/Vincent-Gramoli.jpeg" width="130" height="130">
[vincent.gramoli@sydney.edu.au](mailto:vincent.gramoli@sydney.edu.au)
School of Computer Science
The University of Sydney
1, Cleveland St. NSW 2000 Sydney
Australia
